selenium-hub:
  build: hub

firefox:
  build: node/firefox
  environment:
    HUB_HOST: selenium-hub
    HUB_PORT: 4444
  links:
  - selenium-hub:selenium-hub

chrome:
  build: node/chrome
  environment:
    HUB_HOST: selenium-hub
    HUB_PORT: 4444
  links:
  - selenium-hub:selenium-hub

app:
  build: .
  links:
  - selenium-hub:selenium-hub
  ports:
  - 8080:8080