selenium-hub:
  image: selenium/hub
  ports:
  - 4444:4444
  - 5555:5555

chrome:
  image: selenium/node-chrome
  environment:
    HUB_HOST: selenium-hub
  volumes:
  - /dev/shm:/dev/shm

firefox:
  image: selenium/node-firefox
  environment:
    HUB_HOST: selenium-hub
  # links:
  # - selenium-hub:hub
