apiVersion: "v1"
kind: "ImageStream"
metadata:
  name: "dlb-openshift-base"
spec:
  dockerImageRepository: "rhel7.4"
  tags:
    - name: "7"
      from:
        kind: DockerImage
        name: rhel7.4:latest