apiVersion: "v1"
kind: "ImageStream"
metadata:
  name: "dlb-openshift-base"
spec:
  dockerImageRepository: "registry.access.redhat.com/rhel"
  tags:
    - name: "7"
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/rhel7:7.4"
