apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: selenium-test
      application.name: liveness-monitoring 
    name: selenium-test
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      io.kompose.service: selenium-test
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: firefox
      application.name: liveness-monitoring 
    name: firefox
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 5555
      targetPort: 0
    selector:
      io.kompose.service: firefox
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      application.name: liveness-monitoring 
      io.kompose.service: selenium-hub
    name: selenium-hub
  spec:
    ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
    selector:
      io.kompose.service: selenium-hub
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: selenium-test
      application.name: liveness-monitoring 
      app: Selenium-Liveness
    name: selenium-test
  spec:
    replicas: 1
    selector:
      io.kompose.service: selenium-test
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: selenium-test
          application.name: liveness-monitoring 
      spec:
        containers:
        - image: ' '
          name: selenium-test
          ports:
          - containerPort: 8080
          resources: {}
          command: ["java"]
          args: ["-Dspring.profiles.active=openshift", "-jar", "/app/app.war"]
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - selenium-test
        from:
          kind: ImageStreamTag
          name: selenium-test:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: selenium-test
      application.name: liveness-monitoring 
    name: selenium-test
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: selenium-test
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: selenium-test
      application.name: liveness-monitoring 
    name: selenium-test
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: selenium-test:latest
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/tw5860/seleniumOnOS.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "grape-spring-boot-base-image:latest"
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: firefox
      application.name: liveness-monitoring 
      app: Selenium-Liveness
    name: firefox
  spec:
    replicas: 1
    selector:
      io.kompose.service: firefox
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: firefox
          application.name: liveness-monitoring 
      spec:
        containers:
        - env:
          - name: HUB_HOST
            value: selenium-hub.myproject.svc
          - name: HUB_PORT
            value: "4444"
          - name: HOME
            value: /firefox
          image: ' '
          name: firefox
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          volumeMounts:
            - mountPath: /firefox
              name: home-volume
        restartPolicy: Always
        volumes:
          - name: home-volume
            emptyDir: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - firefox
        from:
          kind: ImageStreamTag
          name: firefox:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: firefox
      application.name: liveness-monitoring 
    name: firefox
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: firefox
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: firefox
      application.name: liveness-monitoring 
    name: firefox
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: firefox:latest
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    runPolicy: Serial
    source:
      contextDir: node/firefox/
      git:
        ref: master
        uri: https://github.com/tw5860/seleniumOnOS.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "rhel7.4:latest"
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: chrome
      application.name: liveness-monitoring 
      app: Selenium-Liveness
    name: chrome
  spec:
    replicas: 1
    selector:
      io.kompose.service: chrome
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: chrome
          application.name: liveness-monitoring 
      spec:
        containers:
        - env:
          - name: HUB_HOST
            value: selenium-hub.myproject.svc
          - name: HUB_PORT
            value: "4444"
          - name: HOME
            value: /chrome
          image: ' '
          name: chrome
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          volumeMounts:
            - mountPath: /chrome
              name: home-volume
        restartPolicy: Always
        volumes:
          - name: home-volume
            emptyDir: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - chrome
        from:
          kind: ImageStreamTag
          name: chrome:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      application.name: liveness-monitoring 
      io.kompose.service: chrome
    name: chrome
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: chrome
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: chrome
      application.name: liveness-monitoring 
    name: chrome
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: chrome:latest
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    runPolicy: Serial
    source:
      contextDir: node/chrome/
      git:
        ref: master
        uri: https://github.com/tw5860/seleniumOnOS.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "rhel7.4:latest"
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: selenium-hub
      application.name: liveness-monitoring 
      app: Selenium-Liveness
    name: selenium-hub
  spec:
    replicas: 1
    selector:
      io.kompose.service: selenium-hub
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: selenium-hub
          application.name: liveness-monitoring 
      spec:
        containers:
        - image: ' '
          name: selenium-hub
          ports:
          - containerPort: 4444
          resources: {}
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - selenium-hub
        from:
          kind: ImageStreamTag
          name: selenium-hub:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: selenium-hub
      application.name: liveness-monitoring 
    name: selenium-hub
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: selenium-hub
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --provider openshift --build
        build-config --build-repo https://github.com/tw5860/seleniumOnOS.git -o selenium-liveness.yaml
      kompose.version: 1.9.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: selenium-hub
      application.name: liveness-monitoring 
    name: selenium-hub
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: selenium-hub:latest
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    runPolicy: Serial
    source:
      contextDir: hub/
      git:
        ref: master
        uri: https://github.com/tw5860/seleniumOnOS.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "rhel7.4:latest"
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Route
  metadata:
    name: google-liveness
  spec:
    port:
      targetPort: '8080'
    to:
      kind: Service
      name: selenium-test
      weight: 100

kind: List
metadata: {}

